sudo: required
dist: trusty
matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - ./node_modules/node-firebird-native-api

language: node_js

node_js:
  - '11'

env:
  - CXX=g++-5
  global:
    - PATH="./node_modules/.bin:$PATH"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libtommath0

before_install:
  - sudo apt-get update
  - wget -O Firebird-3.0.3.32900-0.amd64.tar.gz "https://github.com/FirebirdSQL/firebird/releases/download/R3_0_3/Firebird-3.0.3.32900-0.amd64.tar.gz"
  - tar xzvf Firebird-[0-9]*.tar.gz
  - (cd Firebird-[0-9]*; sudo ./install.sh -silent)
  - sudo usermod -a -G firebird travis

install:
  - travis_wait sg firebird -c "yarn install --frozen-lockfile"
#  - yarn run bootstrap

script:
  - cd ./src/gdmn-front && travis_wait yarn run ci:build # lerna run ci:build --scope gdmn-front

notifications:
  email:
    on_failure: never # always
    on_success: never
  webhooks:
    on_success: true
    on_failure: true
    on_start: true

branches:
  only:
    - travis

git:
  depth: 1
