# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

sudo: false
dist: trusty

language: node_js

node_js:
  - '11'
  - '10'

env:
  - CXX=g++-5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libtommath0

install:
  - wget -O Firebird-3.0.3.32900-0.amd64.tar.gz "https://github.com/FirebirdSQL/firebird/releases/download/R3_0_3/Firebird-3.0.3.32900-0.amd64.tar.gz"
  - tar xzvf Firebird-3.0.3.32900-0.amd64.tar.gz
  - (cd Firebird-3.0.3.32900-0.amd64; sudo ./install.sh -silent)
  - sudo usermod -a -G firebird travis

script:
  - sg firebird -c "yarn"

#matrix:
#  include:
#    - os: osx
#      osx_image: xcode9.2

#notifications:
#  email:
#    on_failure: always
#    on_success: never

#script:
#  - lerna run ci:build --scope gdmn-front
